### ISSUE TITLE
 RangeError: Trying to access beyond buffer length

### ISSUE THREAD

**Issue by manarfalah** [calvinmetcalf/shapefile-js#204] opened 2024-02-19 11:26 UTC
` GeoJSON: RangeError: Trying to access beyond buffer length
    at checkOffset (index.js:1098:36)
    at Uint8Array.readDoubleLE (index.js:1248:18)
    at ParseShp.parseCoord (parseShp.js:215:53)
    at push../node_modules/shpjs/lib/parseShp.js.ParseShp.parsePointArray (parseShp.js:40:19)
    at push../node_modules/shpjs/lib/parseShp.js.ParseShp.parsePolyline (parseShp.js:146:28)
    at push../node_modules/shpjs/lib/parseShp.js.ParseShp.parsePolygon (parseShp.js:196:30)
    at push../node_modules/shpjs/lib/parseShp.js.ParseShp.getRows (parseShp.js:278:21)
    at new ParseShp (parseShp.js:235:20)
    at push../node_modules/shpjs/lib/parseShp.js.module.exports (parseShp.js:304:10)
    at push../node_modules/shpjs/lib/index.js.shp.parseShp (index.js:178:10)
`

**Comment by MarkySparky** [comment] 2024-04-05 10:07
I also have this error - the zipped file works in QGIS and other. File is 165k, contains dbf, prj, shp, shx.

**Comment by STILLMOREzzz** [comment] 2024-04-29 07:12
I hava the same error. The shapfile data works in arcmap.

**Comment by calvinmetcalf** [comment] 2024-04-29 13:41
anyone able to give me a copy of the zipped shapefile that is causing the problem?  Also are we all on version 5.0.0 when we're seeing this issue ?

**Comment by STILLMOREzzz** [comment] 2024-04-30 01:19
Here is my data. I use shp.combine([shp.parseShp(pointshp), shp.parseDbf(pointdbf)]) to parse the shapefile, but it doesn't work.
[shapefiles.zip](https://github.com/calvinmetcalf/shapefile-js/files/15156572/shapefiles.zip)

**Comment by calvinmetcalf** [comment] 2024-04-30 17:18
@STILLMOREzzz  you mind if i include that file in a test?

**Comment by calvinmetcalf** [comment] 2024-04-30 17:52
btw the root issue is that the shapefile is claiming to be shorter than it actually is, in your example @STILLMOREzzz  your file is 5784 bytes long but the header says it's only 5712

**Comment by STILLMOREzzz** [comment] 2024-05-06 01:19
> @STILLMOREzzz you mind if i include that file in a test?
I dont't mind. You can use this data as example.

**Comment by STILLMOREzzz** [comment] 2024-05-06 08:24
@calvinmetcalf  can you tell me how to fix this problem?

**Comment by calvinmetcalf** [comment] 2024-05-06 11:14
The problem is caused by a malformed shape file that says it's shorter then
it really is, I have a fix ready but was waiting on hearing from you about
whether I could include your file in the tests

**Comment by calvinmetcalf** [comment] 2024-05-06 11:15
So I should have something published later today

**Comment by calvinmetcalf** [comment] 2024-05-07 14:00
fixed in v5.0.1

**Closed as completed by calvinmetcalf** 2024-05-07 14:00 UTC
